### ISSUE TITLE
Hadith project

### ISSUE THREAD

**Issue by fawazahmed0** [fawazahmed0/hadiths#10]
Solves: multiple grades, free api, mulitple translations

- [x] fawazahmed0/hadiths#11  (2-3 hrs)
- [x] fawazahmed0/hadiths#9 (urdu fetch)
- [x] see issues at sunnah github and also my q api issues to avoid any mistakes when making things & see sunnah api design & qapi 
- [x] add esitmations & complete asap (deadline)
- [x] fawazahmed0/hadiths#7  (4hrs)
- [x] documentation (1hr)
- [x] docsaurus for quran & hadith seo, also keep things offline for pwa (not sure) and cron build&deply/month (lunr) fawazahmed0/hadiths#6 (6hrs)
- [x] merge https://github.com/fawazahmed0/version-control & hadith versioned files into hadith-api
