### ISSUE TITLE
design

### ISSUE THREAD

**Issue by fawazahmed0** [fawazahmed0/hadiths#6]
- [x] plan architecture 
- [x] sort & clean up thing
- [x] timebox & deadline
- [x] index(book wise(lang group) page (30mins)
- [x] section page  (30mins)
- [x] single/chap(sec)/full (edition,type,grade unianimous) (30mins)
- [x] grade (filter logic)
- [x] revert changes for previous functinality
- [x] [seo listing gen](fawazahmed0/hadiths#6)
- [x] individual listing page(so google can find without sitemap generation) (by hadnum with all langs
- [x] only keep single visible to google to avoid duplicates (& get good results) (divide by book(using nums [crc](https://www.npmjs.com/package/crc) 65k pregenerated) & then language) (using noindex tag for pages not required maybe) (isocodes all languages pregenerate) (bookname in query for seo)
- [x] Group by language in single results page for ease
- [x] Easy scroll using jump to lang, and group by lang
- [x] see [seo html attribures like lang & dir etc for single elments](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes)
- [x] add the seo attr in data.html also
- [x] autoget bare edition if not found
- [x] google site search (30mins)
- [x] fallbak
- [x] avoid sitemap, link seo.html page in sections page with name Get Single Hadith with multiple Languages at very bottom
- [x] [sitemap ](fawazahmed0/hadiths#6)(query params)(avoid duplictes for better g-search) (sitemap link to seo page) (30mins)
- [x] run functions after domcontentloaded (see letters script)
- [x] refactor code
- [x] fetch parallel
- [x] mustache template (see letters)
- [x] noindex tag
- [x] seo (dynamic)  (docusaurus)(seei18n, meta tags, frontmatters), see letters proj for seo etc  (30mins)
- [x] use [common tags](fawazahmed0/hadiths#6)
- [x] clean UI
- [x] test
- [x] documentation
- [x] qura (60mins) (try to use old app , code in new page) (new page to search this, keep it at islm-projs)

**design:**
grades and list of graders names and grades
Grades:
albani: ....

publish @ hadiths repo
Deadline: 27-04-22

**Comment by fawazahmed0** [comment]
https://www.marketing-jive.com/2010/04/14-sitemap-best-practices-for.html
rebuild is needed for proper sitemap generation

https://github.com/ekalinin/sitemap.js
`npx sitemap --index --index-base-url https://fawazahmed0.github.io/hadiths/ < listofurl.txt > sitemap.xml`

**Comment by fawazahmed0** [comment]
seo
page with books list
next page with individual hadnumber list
next page with individual hadith (with all langs)

**Comment by fawazahmed0** [comment]
```Search engines rely on the HTML markup such as <h2>, <table>, etc., to understand the structure of your webpage. When Docusaurus renders your pages, semantic markup, e.g. <aside>, <nav>, <main>, are used to divide the different sections of the page, helping the search engine to locate parts like sidebar, navbar, and the main page content.```

**Comment by fawazahmed0** [comment]
search bar in q
footer, see verse by verse link(grouped by verses), page with all chap x verse x links, (chapter name)
seoify same as hadith prof
also add search bar on data single verse listings page
and also maybe on dataseo had proj page (this will help google search visitors to search again)
hide search bars until google indexes the pages

**Comment by fawazahmed0** [comment]
add sections nane in section listing
show section num &  name only if type is section
see margin/padding in phone
